version: "3"

services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chorme:
    image: selenium/node-chrome-debug:3.141.59
    environment:
      - HUB_HOST=selenium-hub






